<?php

return [
    'migrateList' => [
        'field' => [
            'id' => ['text'=>'ID'],
            'city_id' => ['text'=>'城市','options'=>[]],
            'title' => ['text'=>'标题'],
            'type_id' => ['text'=>'移民类型','options'=>[]],
            'invest_id' => ['text'=>'投资类型','options'=>[]],
            'transact_period' => ['text'=>'办理周期'],
            'project_charac' => ['text'=>'项目特点'],
            'live_require' => ['text'=>'居住要求'],
            'identity' => ['text'=>'身份类型'],
            'total_price' => ['text'=>'总价'],
            'sort' => ['text'=>'排序'],
            'status' => ['text'=>'状态','options'=>['1'=>'启用','2'=>'禁用']],
            'created_at' => ['text'=>'创建时间'],
            'updated_at' => ['text'=>'更新时间'],
        ],
        'search' => [
            'id' => ['text'=>'ID','type'=>'input'],
            'title' => ['text'=>'标题','type'=>'input'],
            'status' => ['text'=>'状态','type'=>'select','value'=>[''=>'--请选择--','1'=>'启用','2'=>'禁用']],
            'type_id' => ['text'=>'移民类型','type'=>'select','value'=>[]],
            'invest_id' => ['text'=>'投资类型','type'=>'select','value'=>[]],
        ],
        'button' => [
            'add' => '/migrate/addMigrate',
            'update' => '/migrate/updateMigrate',
            'see' => '/migrate/seeMigrate',
            'delete' => '/migrate/deleteMigrate',
        ],
        'data_url' => '/migrate/migrateList',
    ],
    'addMigrate' => [
        'field' => [
            'city_id' => ['text'=>'城市','type'=>'custom','value'=>'admin.common.add_city_ztree','verify'=>['required']],
            'type_id' => ['text'=>'移民类型','type'=>'select','value'=>[]],
            'invest_id'=>['text'=>'投资类型','type'=>'select','value'=>[]],
            'title'=>['text'=>'标题','type'=>'input','value'=>'','verify'=>['required']],
            'img'=>['text'=>'图片','type'=>'img','value'=>'','verify'=>['required']],
            'project_charac'=>['text'=>'项目特点','type'=>'input','value'=>'','verify'=>['required']],
            'live_require'=>['text'=>'居住要求','type'=>'input','value'=>'','verify'=>['required']],
            'identity'=>['text'=>'身份类型','type'=>'input','value'=>'','verify'=>['required']],
            'face'=>['text'=>'面向人群','type'=>'input','value'=>'','verify'=>['required']],
            'transact_period'=>['text'=>'办理周期','type'=>'input','value'=>'','verify'=>['required']],
            'total_price'=>['text'=>'总价,以万为单位','type'=>'input','value'=>'','verify'=>['required','number']],
//            'user_id'=>['text'=>'团队成员','type'=>'select','value'=>[]],
            'sort'=>['text'=>'排序','type'=>'input','value'=>'','desc'=>'数值越大，排列越靠前'],
            'status'=>['text'=>'状态','type'=>'radio','value'=>['1'=>'启用','2'=>'禁用'],'verify'=>['required']],
            'publish_date'=>['text'=>'发布时间','type'=>'date','value'=>'','verify'=>['required']],
            'read'=>['text'=>'阅读量','type'=>'input','value'=>''],
            'project_brief'=>['text'=>'项目简介','type'=>'ueditor','value'=>''],
            'project_advantage' => ['text'=>'项目优势','type'=>'ueditor','value'=>''],
            'apply_condition'=>['text'=>'申请条件','type'=>'ueditor','value'=>''],
            'apply_process' => ['text'=>'申请流程','type'=>'ueditor','value'=>''],
        ],
        'sub_url'=>'/migrate/addMigrate',
    ],
    'updateMigrate' => [
        'field' => [
            'city_id' => ['text'=>'城市','type'=>'custom','value'=>'admin.common.add_city_ztree','verify'=>['required']],
            'type_id' => ['text'=>'移民类型','type'=>'select','value'=>[]],
            'invest_id'=>['text'=>'投资类型','type'=>'select','value'=>[]],
            'title'=>['text'=>'标题','type'=>'input','value'=>'','verify'=>['required']],
            'img'=>['text'=>'图片','type'=>'img','value'=>'','verify'=>['required']],
            'project_charac'=>['text'=>'项目特点','type'=>'input','value'=>'','verify'=>['required']],
            'live_require'=>['text'=>'居住要求','type'=>'input','value'=>'','verify'=>['required']],
            'identity'=>['text'=>'身份类型','type'=>'input','value'=>'','verify'=>['required']],
            'face'=>['text'=>'面向人群','type'=>'input','value'=>'','verify'=>['required']],
            'transact_period'=>['text'=>'办理周期','type'=>'input','value'=>'','verify'=>['required']],
            'total_price'=>['text'=>'总价,以万为单位','type'=>'input','value'=>'','verify'=>['required','number']],
//            'user_id'=>['text'=>'团队成员','type'=>'select','value'=>[]],
            'sort'=>['text'=>'排序','type'=>'input','value'=>'','desc'=>'数值越大，排列越靠前'],
            'status'=>['text'=>'状态','type'=>'radio','value'=>['1'=>'启用','2'=>'禁用'],'verify'=>['required']],
            'publish_date'=>['text'=>'发布时间','type'=>'date','value'=>'','verify'=>['required']],
            'read'=>['text'=>'阅读量','type'=>'input','value'=>''],
            'project_brief'=>['text'=>'项目简介','type'=>'ueditor','value'=>''],
            'project_advantage' => ['text'=>'项目优势','type'=>'ueditor','value'=>''],
            'apply_condition'=>['text'=>'申请条件','type'=>'ueditor','value'=>''],
            'apply_process' => ['text'=>'申请流程','type'=>'ueditor','value'=>''],
        ],
        'sub_url' => '/migrate/updateMigrate'
    ],
    'seeMigrate' => [
        'field' => [
            'id' => ['text'=>'ID','type'=>'span'],
            'city_id' => ['text'=>'城市','type'=>'span'],
            'type_id' => ['text'=>'移民类型','type'=>'span',],
            'invest_id'=>['text'=>'投资类型','type'=>'span',],
            'title'=>['text'=>'标题','type'=>'span'],
            'img'=>['text'=>'封面图','type'=>'img'],
            'project_charac'=>['text'=>'项目特点','type'=>'span'],
            'live_require'=>['text'=>'居住要求','type'=>'span'],
            'identity'=>['text'=>'身份类型','type'=>'span'],
            'face'=>['text'=>'面向人群','type'=>'span'],
            'transact_period'=>['text'=>'办理周期','type'=>'span'],
            'total_price'=>['text'=>'总价','type'=>'span'],
//            'user_id'=>['text'=>'跟踪的团队成员','type'=>'span'],
            'project_brief'=>['text'=>'项目简介','type'=>'content'],
            'project_advantage'=>['text'=>'项目优势','type'=>'content'],
            'apply_condition'=>['text'=>'申请条件','type'=>'content'],
            'apply_process'=>['text'=>'申请流程','type'=>'content'],
            'sort'=>['text'=>'排序','type'=>'span'],
            'status'=>['text'=>'状态','type'=>'select','value'=>['1'=>'启用','2'=>'禁用']],
            'read'=>['text'=>'阅读量','type'=>'span'],
//            'real_read'=>['text'=>'真实阅读量','type'=>'span'],
            'publish_date'=>['text'=>'发布时间','type'=>'span'],
            'updated_at' => ['text'=>'更新时间','type'=>'span'],
            'created_at' => ['text'=>'创建时间','type'=>'span'],
        ],
    ],
];
?>